server:
  port: 8082
token:
  signing:
    key: 123123456456789789123123456456789789123123456456789789

spring:
  application:
    name: social-network-post
  datasource:
    url: jdbc:postgresql://localhost:5432/social-network-post
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      schema: post_schema
      connection-init-sql: create schema if not exists post_schema
      connection-timeout: 10000
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
