server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/post_db?currentSchema=public
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
